/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pacote_Leoticia_Saber_Shop;

import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Gnutzmann
 */
public class Form_Leoticia_Saber_Shop extends javax.swing.JFrame {

    /**
     * Creates new form Form_Leoticia_Saber_Shop
     */
    public Form_Leoticia_Saber_Shop() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_corpo = new javax.swing.ButtonGroup();
        buttonGroup_cor = new javax.swing.ButtonGroup();
        jPanel_corpo = new javax.swing.JPanel();
        jRadioButton_graflex = new javax.swing.JRadioButton();
        jRadioButton_fury = new javax.swing.JRadioButton();
        jRadioButton_mauler = new javax.swing.JRadioButton();
        jPanel_cor = new javax.swing.JPanel();
        jRadioButton_verde = new javax.swing.JRadioButton();
        jRadioButton_azul = new javax.swing.JRadioButton();
        jRadioButton_vermelho = new javax.swing.JRadioButton();
        jLabel_Titulo = new javax.swing.JLabel();
        jPanel_atributos = new javax.swing.JPanel();
        jCheckBox_agilidade = new javax.swing.JCheckBox();
        jCheckBox_ataque = new javax.swing.JCheckBox();
        jCheckBox_defesa = new javax.swing.JCheckBox();
        jCheckBox_estabilidade = new javax.swing.JCheckBox();
        jCheckBox_penetracao = new javax.swing.JCheckBox();
        jCheckBox_durabilidade = new javax.swing.JCheckBox();
        jPanel_escolha = new javax.swing.JPanel();
        jButton_comprar = new javax.swing.JButton();
        jButton_limpar = new javax.swing.JButton();
        jButton_sair = new javax.swing.JButton();
        jLabel_total = new javax.swing.JLabel();
        jTextField_total = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane_escolha = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel_saber = new javax.swing.JLabel();
        jLabel_Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Leoticia's Saber Store!");
        setPreferredSize(new java.awt.Dimension(810, 643));
        getContentPane().setLayout(null);

        jPanel_corpo.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecione o corpo:"));

        buttonGroup_corpo.add(jRadioButton_graflex);
        jRadioButton_graflex.setText("Graflex");
        jRadioButton_graflex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_graflexActionPerformed(evt);
            }
        });

        buttonGroup_corpo.add(jRadioButton_fury);
        jRadioButton_fury.setText("Fury");
        jRadioButton_fury.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_furyActionPerformed(evt);
            }
        });

        buttonGroup_corpo.add(jRadioButton_mauler);
        jRadioButton_mauler.setText("Mauler");
        jRadioButton_mauler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_maulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_corpoLayout = new javax.swing.GroupLayout(jPanel_corpo);
        jPanel_corpo.setLayout(jPanel_corpoLayout);
        jPanel_corpoLayout.setHorizontalGroup(
            jPanel_corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_corpoLayout.createSequentialGroup()
                .addGroup(jPanel_corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton_graflex)
                    .addComponent(jRadioButton_mauler)
                    .addComponent(jRadioButton_fury))
                .addGap(0, 119, Short.MAX_VALUE))
        );
        jPanel_corpoLayout.setVerticalGroup(
            jPanel_corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_corpoLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jRadioButton_graflex)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_fury)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_mauler)
                .addContainerGap())
        );

        getContentPane().add(jPanel_corpo);
        jPanel_corpo.setBounds(40, 60, 200, 152);

        jPanel_cor.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecione o cor:"));

        buttonGroup_cor.add(jRadioButton_verde);
        jRadioButton_verde.setText("Verde");
        jRadioButton_verde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_verdeActionPerformed(evt);
            }
        });

        buttonGroup_cor.add(jRadioButton_azul);
        jRadioButton_azul.setText("Azul");
        jRadioButton_azul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_azulActionPerformed(evt);
            }
        });

        buttonGroup_cor.add(jRadioButton_vermelho);
        jRadioButton_vermelho.setText("Vermelho");
        jRadioButton_vermelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_vermelhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_corLayout = new javax.swing.GroupLayout(jPanel_cor);
        jPanel_cor.setLayout(jPanel_corLayout);
        jPanel_corLayout.setHorizontalGroup(
            jPanel_corLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_corLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_corLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton_verde)
                    .addComponent(jRadioButton_azul)
                    .addComponent(jRadioButton_vermelho))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel_corLayout.setVerticalGroup(
            jPanel_corLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_corLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_verde)
                .addGap(27, 27, 27)
                .addComponent(jRadioButton_vermelho)
                .addGap(27, 27, 27)
                .addComponent(jRadioButton_azul)
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel_cor);
        jPanel_cor.setBounds(40, 230, 200, 200);

        jLabel_Titulo.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_Titulo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pacote_Leoticia_Saber_Shop/coollogo_com-7391098.png"))); // NOI18N
        getContentPane().add(jLabel_Titulo);
        jLabel_Titulo.setBounds(280, 10, 210, 50);

        jPanel_atributos.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecione os atributos:"));

        jCheckBox_agilidade.setText("Agilidade");
        jCheckBox_agilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_agilidadeActionPerformed(evt);
            }
        });

        jCheckBox_ataque.setText("Ataque");
        jCheckBox_ataque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_ataqueActionPerformed(evt);
            }
        });

        jCheckBox_defesa.setText("Defesa");
        jCheckBox_defesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_defesaActionPerformed(evt);
            }
        });

        jCheckBox_estabilidade.setText("Estabilidade");
        jCheckBox_estabilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_estabilidadeActionPerformed(evt);
            }
        });

        jCheckBox_penetracao.setText("Penetração");
        jCheckBox_penetracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_penetracaoActionPerformed(evt);
            }
        });

        jCheckBox_durabilidade.setText("Durabilidade");
        jCheckBox_durabilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_durabilidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_atributosLayout = new javax.swing.GroupLayout(jPanel_atributos);
        jPanel_atributos.setLayout(jPanel_atributosLayout);
        jPanel_atributosLayout.setHorizontalGroup(
            jPanel_atributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_atributosLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel_atributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_defesa)
                    .addComponent(jCheckBox_durabilidade)
                    .addComponent(jCheckBox_penetracao)
                    .addComponent(jCheckBox_estabilidade)
                    .addComponent(jCheckBox_agilidade)
                    .addComponent(jCheckBox_ataque))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel_atributosLayout.setVerticalGroup(
            jPanel_atributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_atributosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox_agilidade)
                .addGap(36, 36, 36)
                .addComponent(jCheckBox_ataque)
                .addGap(33, 33, 33)
                .addComponent(jCheckBox_defesa)
                .addGap(35, 35, 35)
                .addComponent(jCheckBox_durabilidade)
                .addGap(33, 33, 33)
                .addComponent(jCheckBox_estabilidade)
                .addGap(40, 40, 40)
                .addComponent(jCheckBox_penetracao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_atributos);
        jPanel_atributos.setBounds(520, 60, 240, 370);

        jPanel_escolha.setBorder(javax.swing.BorderFactory.createTitledBorder("Escolha do Jedi:"));

        jButton_comprar.setText("Comprar");
        jButton_comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_comprarActionPerformed(evt);
            }
        });

        jButton_limpar.setText("Limpar");
        jButton_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_limparActionPerformed(evt);
            }
        });

        jButton_sair.setText("Sair");
        jButton_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sairActionPerformed(evt);
            }
        });

        jLabel_total.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_total.setText("Total do pedido:");

        jTextField_total.setEditable(false);
        jTextField_total.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextPane_escolha.setEditable(false);
        jScrollPane1.setViewportView(jTextPane_escolha);

        javax.swing.GroupLayout jPanel_escolhaLayout = new javax.swing.GroupLayout(jPanel_escolha);
        jPanel_escolha.setLayout(jPanel_escolhaLayout);
        jPanel_escolhaLayout.setHorizontalGroup(
            jPanel_escolhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_escolhaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_escolhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_sair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_limpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_comprar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_escolhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_escolhaLayout.createSequentialGroup()
                        .addComponent(jLabel_total)
                        .addGap(0, 114, Short.MAX_VALUE))
                    .addComponent(jTextField_total))
                .addContainerGap())
        );
        jPanel_escolhaLayout.setVerticalGroup(
            jPanel_escolhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_escolhaLayout.createSequentialGroup()
                .addGroup(jPanel_escolhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_escolhaLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel_escolhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_comprar)
                            .addComponent(jLabel_total))
                        .addComponent(jTextField_total, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_escolhaLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jButton_limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_sair)))
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_escolhaLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        getContentPane().add(jPanel_escolha);
        jPanel_escolha.setBounds(40, 440, 720, 150);

        jLabel_saber.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_saber.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_saber.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_saber, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_saber, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(290, 70, 190, 345);

        jLabel_Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pacote_Leoticia_Saber_Shop/image18.png"))); // NOI18N
        getContentPane().add(jLabel_Fundo);
        jLabel_Fundo.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox_penetracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_penetracaoActionPerformed
        // TODO add your handling code here:
        if(jCheckBox_penetracao.isSelected())
        {
            atributo+=6900;
        }
        
    }//GEN-LAST:event_jCheckBox_penetracaoActionPerformed

    private void jRadioButton_maulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_maulerActionPerformed
        // TODO add your handling code here:
        if(jRadioButton_mauler.isSelected())
        corpo=250000;
        visualizar();
    }//GEN-LAST:event_jRadioButton_maulerActionPerformed

    private void jRadioButton_azulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_azulActionPerformed
        // TODO add your handling code here:
         if(jRadioButton_azul.isSelected())
             cores=30000;
         visualizar();
    }//GEN-LAST:event_jRadioButton_azulActionPerformed

    private void jRadioButton_graflexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_graflexActionPerformed
        // TODO add your handling code here:
         if(jRadioButton_graflex.isSelected())
        corpo=300000;
         visualizar();
    }//GEN-LAST:event_jRadioButton_graflexActionPerformed

    public void ImagemIcon()
    {
        //ImageIcon img = new ImageIcon (getClass().getResource("fury_azul"));
    }
    
    
    private int total=0;
    private int cores=0;
    private int atributo=0;
    private int corpo=0;
    private void jButton_comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_comprarActionPerformed
        // TODO add your handling code here:
        int confi1=0;
        int confi2=2;
        String corpo1 = null;
        String cor1= null;
        String atributo1= null;
        String texto = null;
        int atri=0;
        if(jRadioButton_azul.isSelected() || jRadioButton_verde.isSelected() || jRadioButton_vermelho.isSelected())
            confi1=1;
        if(jRadioButton_fury.isSelected() || jRadioButton_graflex.isSelected() || jRadioButton_mauler.isSelected())
            confi2=1;
        
        if(confi1==confi2)
        {
           
           total= cores+corpo+atributo;
        jTextField_total.setText("R$ "+ total);
        jButton_comprar.setEnabled(false);
        
        
        if(jRadioButton_fury.isSelected())
            corpo1="Fury";
        if(jRadioButton_graflex.isSelected())
            corpo1="Graflex";
        if(jRadioButton_mauler.isSelected())
            corpo1="Mauler";
        if(jRadioButton_azul.isSelected())
            cor1="azul";
        if(jRadioButton_verde.isSelected())
            cor1="verde";
        if(jRadioButton_vermelho.isSelected())
            cor1="vermelho";
        texto="Sabre de luz com corpo " +corpo1 + " na cor " +cor1 ;
        if(jCheckBox_agilidade.isSelected() || 
           jCheckBox_ataque.isSelected() || 
           jCheckBox_defesa.isSelected() || 
           jCheckBox_durabilidade.isSelected() || 
           jCheckBox_estabilidade.isSelected() || 
           jCheckBox_penetracao.isSelected())
        {
            texto+=" melhorado em"; 
        }
        
        atributo1="";
        
        if(jCheckBox_agilidade.isSelected())
        {
            atributo1+=" agilidade";
            atri++;
            texto +=atributo1;
        }
        
        if(jCheckBox_ataque.isSelected())
        {
            atributo1=" ataque";
            if(atri==1)
            {
                texto+= "," + atributo1;
            }
            else
            {
                atri++;
                texto+="" +atributo1;
            }
        }
        
        if(jCheckBox_defesa.isSelected())
        {
            atributo1=" defesa";
            if(atri==1)
            {
                texto+= "," + atributo1;
            }
            else
            {
                atri++;
                texto+="" +atributo1;
            }
        }
        
        if(jCheckBox_durabilidade.isSelected())
        {
            atributo1=" durabilidade";
            if(atri==1)
            {
                texto+= "," + atributo1;
            }
            else
            {
                atri++;
                texto+="" +atributo1;
            }
        }
        
        if(jCheckBox_estabilidade.isSelected())
        {
            atributo1=" estabilidade";
            if(atri==1)
            {
                texto+= "," + atributo1;
            }
            else
            {
                atri++;
                texto+="" +atributo1;
            }
        }
        
        if(jCheckBox_penetracao.isSelected())
        {
            atributo1=" penetração";
            if(atri==1)
            {
                texto+= "," + atributo1;
            }
            else
            {
                atri++;
                texto+="" +atributo1;
            }
        }
        
        jTextPane_escolha.setText(""+texto +"."); 
            
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Voce deve selecionar um corpo e a cor!","Escolha seu sabre!",JOptionPane.WARNING_MESSAGE);
        }
        
       
    }//GEN-LAST:event_jButton_comprarActionPerformed

    private void jRadioButton_furyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_furyActionPerformed
        // TODO add your handling code here:
         if(jRadioButton_fury.isSelected())
         {
             corpo=200000;
             
         }
        
         visualizar();
    }//GEN-LAST:event_jRadioButton_furyActionPerformed

    private void jRadioButton_verdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_verdeActionPerformed
        // TODO add your handling code here:
         if(jRadioButton_verde.isSelected())
             cores=0;
         visualizar();
    }//GEN-LAST:event_jRadioButton_verdeActionPerformed

    private void jRadioButton_vermelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_vermelhoActionPerformed
        // TODO add your handling code here:
         if(jRadioButton_vermelho.isSelected())
             cores=50000;
         visualizar();
    }//GEN-LAST:event_jRadioButton_vermelhoActionPerformed

    private void jButton_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_sairActionPerformed

    private void jCheckBox_agilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_agilidadeActionPerformed
        // TODO add your handling code here:
        if(jCheckBox_agilidade.isSelected())
        {
           atributo+=6500; 
        }
        
    }//GEN-LAST:event_jCheckBox_agilidadeActionPerformed

    private void jCheckBox_ataqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_ataqueActionPerformed
        // TODO add your handling code here:
        if(jCheckBox_ataque.isSelected())
        {
          atributo+=5000;  
        }
        
    }//GEN-LAST:event_jCheckBox_ataqueActionPerformed

    private void jCheckBox_defesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_defesaActionPerformed
        // TODO add your handling code here:
        if(jCheckBox_defesa.isSelected())
        {
            atributo+=5000;
        }
        
    }//GEN-LAST:event_jCheckBox_defesaActionPerformed

    private void jCheckBox_durabilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_durabilidadeActionPerformed
        // TODO add your handling code here:
        if(jCheckBox_durabilidade.isSelected())
        {
          atributo+=6000;  
        }
        
    }//GEN-LAST:event_jCheckBox_durabilidadeActionPerformed

    private void jCheckBox_estabilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_estabilidadeActionPerformed
        // TODO add your handling code here:
        if(jCheckBox_estabilidade.isSelected())
        {
            atributo+=4500;
        }
        
    }//GEN-LAST:event_jCheckBox_estabilidadeActionPerformed

    private void jButton_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_limparActionPerformed
        // TODO add your handling code here:
        buttonGroup_cor.clearSelection();
        buttonGroup_corpo.clearSelection();
        corpo=0;
        atributo=0;
        cores=0;
        jTextField_total.setText(" ");
        jLabel_saber.setIcon(null);
        jTextPane_escolha.setText(" ");
        jCheckBox_agilidade.setSelected(false);
        jCheckBox_ataque.setSelected(false);
        jCheckBox_defesa.setSelected(false);
        jCheckBox_durabilidade.setSelected(false);
        jCheckBox_estabilidade.setSelected(false);
        jCheckBox_penetracao.setSelected(false);
        jButton_comprar.setEnabled(true);
        
    }//GEN-LAST:event_jButton_limparActionPerformed

    private void visualizar()
    {
        if(jRadioButton_fury.isSelected() && jRadioButton_verde.isSelected())
        {
            ImageIcon img = new ImageIcon(getClass().getResource("fury_verde.png"));
            jLabel_saber.setIcon(img);
            
        }
        
        if(jRadioButton_fury.isSelected() && jRadioButton_vermelho.isSelected())
        {
            ImageIcon img = new ImageIcon(getClass().getResource("fury_vermelho.png"));
            jLabel_saber.setIcon(img);
            
        }
        
        if(jRadioButton_fury.isSelected() && jRadioButton_azul.isSelected())
        {
            ImageIcon img = new ImageIcon(getClass().getResource("fury_azul.png"));
            jLabel_saber.setIcon(img);
            
        }
        
        if(jRadioButton_graflex.isSelected() && jRadioButton_verde.isSelected())
        {
            ImageIcon img = new ImageIcon(getClass().getResource("graflex_verde.png"));
            jLabel_saber.setIcon(img);
            
        }
        
        if(jRadioButton_graflex.isSelected() && jRadioButton_vermelho.isSelected())
        {
            ImageIcon img = new ImageIcon(getClass().getResource("graflex_vermelho.png"));
            jLabel_saber.setIcon(img);
            
        }
        
        if(jRadioButton_graflex.isSelected() && jRadioButton_azul.isSelected())
        {
            ImageIcon img = new ImageIcon(getClass().getResource("graflex_azul.png"));
            jLabel_saber.setIcon(img);
            
        }
        
        if(jRadioButton_mauler.isSelected() && jRadioButton_verde.isSelected())
        {
            ImageIcon img = new ImageIcon(getClass().getResource("mauler_verde.png"));
            jLabel_saber.setIcon(img);
            
        }
        
        if(jRadioButton_mauler.isSelected() && jRadioButton_vermelho.isSelected())
        {
            ImageIcon img = new ImageIcon(getClass().getResource("mauler_vermelho.png"));
            jLabel_saber.setIcon(img);
            
        }
        
        if(jRadioButton_mauler.isSelected() && jRadioButton_azul.isSelected())
        {
            ImageIcon img = new ImageIcon(getClass().getResource("mauler_azul.png"));
            jLabel_saber.setIcon(img);
            
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Leoticia_Saber_Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Leoticia_Saber_Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Leoticia_Saber_Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Leoticia_Saber_Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Leoticia_Saber_Shop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_cor;
    private javax.swing.ButtonGroup buttonGroup_corpo;
    private javax.swing.JButton jButton_comprar;
    private javax.swing.JButton jButton_limpar;
    private javax.swing.JButton jButton_sair;
    private javax.swing.JCheckBox jCheckBox_agilidade;
    private javax.swing.JCheckBox jCheckBox_ataque;
    private javax.swing.JCheckBox jCheckBox_defesa;
    private javax.swing.JCheckBox jCheckBox_durabilidade;
    private javax.swing.JCheckBox jCheckBox_estabilidade;
    private javax.swing.JCheckBox jCheckBox_penetracao;
    private javax.swing.JLabel jLabel_Fundo;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_saber;
    private javax.swing.JLabel jLabel_total;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_atributos;
    private javax.swing.JPanel jPanel_cor;
    private javax.swing.JPanel jPanel_corpo;
    private javax.swing.JPanel jPanel_escolha;
    private javax.swing.JRadioButton jRadioButton_azul;
    private javax.swing.JRadioButton jRadioButton_fury;
    private javax.swing.JRadioButton jRadioButton_graflex;
    private javax.swing.JRadioButton jRadioButton_mauler;
    private javax.swing.JRadioButton jRadioButton_verde;
    private javax.swing.JRadioButton jRadioButton_vermelho;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField_total;
    private javax.swing.JTextPane jTextPane_escolha;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("darth.png")));
    }
}
